<?php
$arUrlRewrite = array(
  10 => [
    'CONDITION' => '#^/bitrix/services/ymarket/#',
    'RULE' => '',
    'ID' => '',
    'PATH' => '/bitrix/services/ymarket/index.php',
    'SORT' => 10,
  ],
  20 => [
    'CONDITION' => '#^/rest/#',
    'RULE' => '',
    'ID' => '',
    'PATH' => '/bitrix/services/rest/index.php',
    'SORT' => 20,
  ],
  30 => [
    'CONDITION' => '#^/blog/#',
    'RULE' => '',
    'ID' => 'bitrix:news',
    'PATH' => '/blog/index.php',
    'SORT' => 30,
  ],
  40 => [
    'CONDITION' => '#^/developery/([^/]+?)/reviews/(\?(.*))?#',
    'RULE' => 'CODE=$1',
    'ID' => 'bitrix:highloadblock.view',
    'PATH' => '/developery/reviews.php',
    'SORT' => 40,
  ],
  50 => [
    'CONDITION' => '#^/developery/([^/]+?)/map/(\?(.*))?#',
    'RULE' => 'DEVELOPER_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 50,
  ],
  60 => [
    'CONDITION' => '#^/developery/([^/]+?)/(\?(.*))?#',
    'RULE' => 'CODE=$1',
    'ID' => 'bitrix:highloadblock.view',
    'PATH' => '/developery/detail.php',
    'SORT' => 60,
  ],
  70 => [
    'CONDITION' => '#^/poselki/filter/(.+?)/apply/map/(\?(.*))?#',
    'RULE' => 'SMART_FILTER_PATH=$1&$2',
    'ID' => 'bitrix:catalog.smart.filter',
    'PATH' => '/map/index.php',
    'SORT' => 70,
  ],
  80 => [
    'CONDITION' => '#^/poselki/kupit-dachnyj-uchastok/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_CODE=dachnye',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 80,
  ],
  90 => [
    'CONDITION' => '#^/poselki/kupit-dachnyj-dom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_CODE=dachnye',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 90,
  ],
  100 => [
    'CONDITION' => '#^/poselki/dachnye/map/(\?(.*))?#',
    'RULE' => 'TYPE_CODE=dachnye',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 100,
  ],
  110 => [
    'CONDITION' => '#^/poselki/kupit-kottedzhnyj-uchastok/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_CODE=kottedzhnye',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 110,
  ],
  120 => [
    'CONDITION' => '#^/poselki/kupit-kottedzh/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_CODE=kottedzhnye',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 120,
  ],
  130 => [
    'CONDITION' => '#^/poselki/kottedzhnye/map/(\?(.*))?#',
    'RULE' => 'TYPE_CODE=kottedzhnye',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 130,
  ],
  140 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-([^/]+?)-class/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&CLASS_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 140,
  ],
  150 => [
    'CONDITION' => '#^/poselki/kupit-dom-([^/]+?)-class/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&CLASS_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 150,
  ],
  160 => [
    'CONDITION' => '#^/poselki/([^/]+?)-class/map/(\?(.*))?#',
    'RULE' => 'CLASS_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 160,
  ],
  170 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-([0-9]+?)-sotok/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&AREA_TYPE=sotok&AREA_URL=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 170,
  ],
  180 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-([0-9]+?)-sotki/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&AREA_TYPE=sotki&AREA_URL=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 180,
  ],
  190 => [
    'CONDITION' => '#^/poselki/kupit-dom-na-([0-9]+?)-sotkah/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&AREA_TYPE=sotkah&AREA_URL=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 190,
  ],
  200 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/do-([0-9]+?)-km-kad-do-([0-9]+?)-tysyach/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=tys&MKAD_KM=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 200,
  ],
  210 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/do-([0-9]+?)-km-kad-do-([0-9,]+?)-milliona/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=mln&MKAD_KM=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 210,
  ],
  220 => [
    'CONDITION' => '#^/poselki/kupit-dom/do-([0-9]+?)-km-kad-do-([0-9,]+?)-milliona/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&PRICE_TYPE=mln&MKAD_KM=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 220,
  ],
  230 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-do-([0-9]+?)-tysyach/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=tys&SHOSSE_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 230,
  ],
  240 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-do-([0-9,]+?)-milliona/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=mln&SHOSSE_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 240,
  ],
  250 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-do-([0-9,]+?)-milliona/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&PRICE_TYPE=mln&SHOSSE_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 250,
  ],
  260 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-do-([0-9]+?)-tysyach/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=tys&RAYON_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 260,
  ],
  270 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-do-([0-9,]+?)-milliona/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=mln&RAYON_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 270,
  ],
  280 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-rayon-do-([0-9,]+?)-milliona/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&PRICE_TYPE=mln&RAYON_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 280,
  ],
  290 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-do-([0-9]+?)-tys-rub/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=tys&PRICE_URL=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 290,
  ],
  300 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-do-([0-9,]+?)-mln-rub/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=mln&PRICE_URL=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 300,
  ],
  310 => [
    'CONDITION' => '#^/poselki/kupit-dom-do-([0-9,]+?)-mln-rub/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&PRICE_TYPE=mln&PRICE_URL=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 310,
  ],
  320 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-do-([0-9]+?)-km-ot-kad/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 320,
  ],
  330 => [
    'CONDITION' => '#^/poselki/kupit-dom-dachu-kottedzh-do-([0-9]+?)-km-ot-kad/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 330,
  ],
  340 => [
    'CONDITION' => '#^/poselki/do-([0-9]+?)-km-ot-kad/map/(\?(.*))?#',
    'RULE' => 'MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 340,
  ],
  350 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/kommunikatsii-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=kommunikaciyami&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 350,
  ],
  360 => [
    'CONDITION' => '#^/poselki/kupit-dom/kommunikatsii-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=kommunikaciyami&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 360,
  ],
  370 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/svet-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=elektrichestvom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 370,
  ],
  380 => [
    'CONDITION' => '#^/poselki/kupit-dom/svet-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=elektrichestvom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 380,
  ],
  390 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/gaz-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=gazom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 390,
  ],
  400 => [
    'CONDITION' => '#^/poselki/kupit-dom/gaz-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=gazom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 400,
  ],
  410 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/voda-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=vodoprovodom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 410,
  ],
  420 => [
    'CONDITION' => '#^/poselki/kupit-dom/voda-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=vodoprovodom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 420,
  ],
  430 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-kommunikatsii/map/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 430,
  ],
  440 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-kommunikatsii/map/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 440,
  ],
  450 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-kommunikatsii/map/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 450,
  ],
  460 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-svet/map/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 460,
  ],
  470 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-svet/map/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 470,
  ],
  480 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-svet/map/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 480,
  ],
  490 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-gaz/map/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 490,
  ],
  500 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-gaz/map/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 500,
  ],
  510 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-gaz/map/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 510,
  ],
  520 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-voda/map/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 520,
  ],
  530 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-voda/map/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 530,
  ],
  540 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-voda/map/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 540,
  ],
  550 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'MKAD_KM=$2&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 550,
  ],
  560 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'MKAD_KM=$2&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 560,
  ],
  570 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'SHOSSE_CODE=$1&MKAD_KM=$2',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 570,
  ],
  580 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-ryadom-s-lesom/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-s-lesom&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 580,
  ],
  590 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-ryadom-s-lesom/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-s-lesom&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 590,
  ],
  600 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-ryadom-s-lesom/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-s-lesom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 600,
  ],
  610 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-u-vody/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-vody&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 610,
  ],
  620 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-u-vody/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-vody&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 620,
  ],
  630 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-u-vody/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-vody&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 630,
  ],
  640 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-snt/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=snt&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 640,
  ],
  650 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-snt/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=snt&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 650,
  ],
  660 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-snt/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=snt&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 660,
  ],
  670 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-izhs/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=izhs&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 670,
  ],
  680 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-izhs/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=izhs&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 680,
  ],
  690 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-izhs/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=izhs&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 690,
  ],
  700 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse/kupit-uchastok/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 700,
  ],
  710 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse/kupit-dom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 710,
  ],
  720 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse/map/(\?(.*))?#',
    'RULE' => 'SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 720,
  ],
  730 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-kommunikatsii/map/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&DOMA_CODE=noDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 730,
  ],
  740 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-rayon-kommunikatsii/map/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&DOMA_CODE=withDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 740,
  ],
  750 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon-kommunikatsii/map/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 750,
  ],
  760 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-svet/map/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&DOMA_CODE=noDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 760,
  ],
  770 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-rayon-svet/map/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&DOMA_CODE=withDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 770,
  ],
  780 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon-svet/map/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 780,
  ],
  790 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-gaz/map/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&DOMA_CODE=noDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 790,
  ],
  800 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-rayon-gaz/map/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&DOMA_CODE=withDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 800,
  ],
  810 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon-gaz/map/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 810,
  ],
  820 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-voda/map/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&DOMA_CODE=noDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 820,
  ],
  830 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-rayon-voda/map/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&DOMA_CODE=withDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 830,
  ],
  840 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon-voda/map/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 840,
  ],
  850 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon/kupit-uchastok/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 850,
  ],
  860 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon/kupit-dom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 860,
  ],
  870 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon/map/(\?(.*))?#',
    'RULE' => 'RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 870,
  ],
  880 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-s-elektrichestvom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=elektrichestvom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 880,
  ],
  890 => [
    'CONDITION' => '#^/poselki/kupit-dom-s-elektrichestvom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=elektrichestvom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 890,
  ],
  900 => [
    'CONDITION' => '#^/poselki/s-elektrichestvom/map/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 900,
  ],
  910 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-s-vodoprovodom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=vodoprovodom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 910,
  ],
  920 => [
    'CONDITION' => '#^/poselki/kupit-dom-s-vodoprovodom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=vodoprovodom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 920,
  ],
  930 => [
    'CONDITION' => '#^/poselki/s-vodoprovodom/map/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 930,
  ],
  940 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-s-gazom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=gazom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 940,
  ],
  950 => [
    'CONDITION' => '#^/poselki/kupit-dom-s-gazom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=gazom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 950,
  ],
  960 => [
    'CONDITION' => '#^/poselki/s-gazom/map/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 960,
  ],
  970 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-s-kommunikaciyami/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=kommunikaciyami',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 970,
  ],
  980 => [
    'CONDITION' => '#^/poselki/kupit-dom-s-kommunikaciyami/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=kommunikaciyami',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 980,
  ],
  990 => [
    'CONDITION' => '#^/poselki/s-kommunikaciyami/map/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 990,
  ],
  1000 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-snt-([^/]+?)-rayon/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=snt&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1000,
  ],
  1010 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-snt/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=snt',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1010,
  ],
  1020 => [
    'CONDITION' => '#^/poselki/kupit-dom-snt-([^/]+?)-rayon/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=snt&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1020,
  ],
  1030 => [
    'CONDITION' => '#^/poselki/kupit-dom-snt/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=snt',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1030,
  ],
  1040 => [
    'CONDITION' => '#^/poselki/snt/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=snt',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1040,
  ],
  1045 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon-snt/map/(\?(.*))?#',
    'RULE' => 'RAYON_CODE=$1&TYPE_URL=snt',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1045,
  ],
  1050 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/do-([0-9]+?)-km-kad-izhs/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=izhs&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1050,
  ],
  1060 => [
    'CONDITION' => '#^/poselki/kupit-dom/do-([0-9]+?)-km-kad-izhs/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=izhs&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1060,
  ],
  1070 => [
    'CONDITION' => '#^/poselki/do-([0-9]+?)-km-kad-izhs/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=izhs&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1070,
  ],
  1080 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-izhs-([^/]+?)-rayon/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=izhs&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1080,
  ],
  1090 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-izhs/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=izhs',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1090,
  ],
  1100 => [
    'CONDITION' => '#^/poselki/kupit-dom-izhs-([^/]+?)-rayon/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=izhs&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1100,
  ],
  1110 => [
    'CONDITION' => '#^/poselki/kupit-dom-izhs/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=izhs',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1110,
  ],
  1120 => [
    'CONDITION' => '#^/poselki/izhs/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=izhs',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1120,
  ],
  1130 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1130,
  ],
  1140 => [
    'CONDITION' => '#^/poselki/kupit-dom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1140,
  ],
  1150 => [
    'CONDITION' => '#^/poselki/ryadom-s-lesom/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-s-lesom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1150,
  ],
  1160 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-ryadom-s-lesom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=ryadom-s-lesom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1160,
  ],
  1170 => [
    'CONDITION' => '#^/poselki/kupit-dom-ryadom-s-lesom/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=ryadom-s-lesom',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1170,
  ],
  1180 => [
    'CONDITION' => '#^/poselki/u-vody/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-vody',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1180,
  ],
  1190 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-u-vody/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=u-vody',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1190,
  ],
  1200 => [
    'CONDITION' => '#^/poselki/kupit-dom-u-vody/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=u-vody',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1200,
  ],
  1210 => [
    'CONDITION' => '#^/poselki/u-ozera/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-ozera',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1210,
  ],
  1220 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-u-ozera/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=u-ozera',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1220,
  ],
  1230 => [
    'CONDITION' => '#^/poselki/kupit-dom-u-ozera/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=u-ozera',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1230,
  ],
  1240 => [
    'CONDITION' => '#^/poselki/u-reki/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-reki',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1240,
  ],
  1250 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-u-reki/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=u-reki',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1250,
  ],
  1260 => [
    'CONDITION' => '#^/poselki/kupit-dom-u-reki/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=u-reki',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1260,
  ],
  1270 => [
    'CONDITION' => '#^/poselki/ryadom-zhd-stanciya/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-zhd-stanciya',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1270,
  ],
  1280 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-ryadom-zhd-stanciya/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=ryadom-zhd-stanciya',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1280,
  ],
  1290 => [
    'CONDITION' => '#^/poselki/kupit-dom-ryadom-zhd-stanciya/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=ryadom-zhd-stanciya',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1290,
  ],
  1300 => [
    'CONDITION' => '#^/poselki/ryadom-avtobusnaya-ostanovka/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-avtobusnaya-ostanovka',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1300,
  ],
  1310 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-ryadom-avtobusnaya-ostanovka/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=ryadom-avtobusnaya-ostanovka',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1310,
  ],
  1320 => [
    'CONDITION' => '#^/poselki/kupit-dom-ryadom-avtobusnaya-ostanovka/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=ryadom-avtobusnaya-ostanovka',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1320,
  ],
  1325 => [
    'CONDITION' => '#^/poselki/promyshlennye/map/(\?(.*))?#',
    'RULE' => 'TYPE_URL=promyshlennye',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1325,
  ],
  1330 => [
    'CONDITION' => '#^/poselki/kupit-dom-([0-9]+?)-kv-m/map/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&PLOTTAGE=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1330,
  ],
  1340 => [
    'CONDITION' => '#^/poselki/kommunikatsii-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1340,
  ],
  1350 => [
    'CONDITION' => '#^/poselki/svet-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1350,
  ],
  1360 => [
    'CONDITION' => '#^/poselki/gaz-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1360,
  ],
  1370 => [
    'CONDITION' => '#^/poselki/voda-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1370,
  ],
  1380 => [
    'CONDITION' => '#^/poselki/map/(\?(.*))?#',
    'RULE' => '',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 1380,
  ],
  1390 => [
    'CONDITION' => '#^/poselki/filter/(.+?)/apply/(\?(.*))?#',
    'RULE' => 'SMART_FILTER_PATH=$1&$2',
    'ID' => 'bitrix:catalog.smart.filter',
    'PATH' => '/poselki/index.php',
    'SORT' => 1390,
  ],
  1400 => [
    'CONDITION' => '#^/poselki/kupit-dachnyj-uchastok/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_CODE=dachnye',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1400,
  ],
  1410 => [
    'CONDITION' => '#^/poselki/kupit-dachnyj-dom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_CODE=dachnye',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1410,
  ],
  1420 => [
    'CONDITION' => '#^/poselki/dachnye/(\?(.*))?#',
    'RULE' => 'TYPE_CODE=dachnye',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1420,
  ],
  1430 => [
    'CONDITION' => '#^/poselki/kupit-kottedzhnyj-uchastok/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_CODE=kottedzhnye',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1430,
  ],
  1440 => [
    'CONDITION' => '#^/poselki/kupit-kottedzh/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_CODE=kottedzhnye',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1440,
  ],
  1450 => [
    'CONDITION' => '#^/poselki/kottedzhnye/(\?(.*))?#',
    'RULE' => 'TYPE_CODE=kottedzhnye',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1450,
  ],
  1460 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-([^/]+?)-class/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&CLASS_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1460,
  ],
  1470 => [
    'CONDITION' => '#^/poselki/kupit-dom-([^/]+?)-class/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&CLASS_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1470,
  ],
  1480 => [
    'CONDITION' => '#^/poselki/([^/]+?)-class/(\?(.*))?#',
    'RULE' => 'CLASS_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1480,
  ],
  1490 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-([0-9]+?)-sotok/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&AREA_TYPE=sotok&AREA_URL=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1490,
  ],
  1500 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-([0-9]+?)-sotki/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&AREA_TYPE=sotki&AREA_URL=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1500,
  ],
  1510 => [
    'CONDITION' => '#^/poselki/kupit-dom-na-([0-9]+?)-sotkah/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&AREA_TYPE=sotkah&AREA_URL=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1510,
  ],
  1520 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/do-([0-9]+?)-km-kad-do-([0-9]+?)-tysyach/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=tys&MKAD_KM=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1520,
  ],
  1530 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/do-([0-9]+?)-km-kad-do-([0-9,]+?)-milliona/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=mln&MKAD_KM=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1530,
  ],
  1540 => [
    'CONDITION' => '#^/poselki/kupit-dom/do-([0-9]+?)-km-kad-do-([0-9,]+?)-milliona/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&PRICE_TYPE=mln&MKAD_KM=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1540,
  ],
  1550 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-do-([0-9]+?)-tysyach/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=tys&SHOSSE_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1550,
  ],
  1560 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-do-([0-9,]+?)-milliona/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=mln&SHOSSE_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1560,
  ],
  1570 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-do-([0-9,]+?)-milliona/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&PRICE_TYPE=mln&SHOSSE_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1570,
  ],
  1580 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-do-([0-9]+?)-tysyach/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=tys&RAYON_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1580,
  ],
  1590 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-do-([0-9,]+?)-milliona/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=mln&RAYON_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1590,
  ],
  1600 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-rayon-do-([0-9,]+?)-milliona/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&PRICE_TYPE=mln&RAYON_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1600,
  ],
  1610 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-do-([0-9]+?)-tys-rub/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=tys&PRICE_URL=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1610,
  ],
  1620 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-do-([0-9,]+?)-mln-rub/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&PRICE_TYPE=mln&PRICE_URL=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1620,
  ],
  1630 => [
    'CONDITION' => '#^/poselki/kupit-dom-do-([0-9,]+?)-mln-rub/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&PRICE_TYPE=mln&PRICE_URL=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1630,
  ],
  1640 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-do-([0-9]+?)-km-ot-kad/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1640,
  ],
  1650 => [
    'CONDITION' => '#^/poselki/kupit-dom-dachu-kottedzh-do-([0-9]+?)-km-ot-kad/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1650,
  ],
  1660 => [
    'CONDITION' => '#^/poselki/do-([0-9]+?)-km-ot-kad/(\?(.*))?#',
    'RULE' => 'MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1660,
  ],
  1670 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/kommunikatsii-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=kommunikaciyami&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1670,
  ],
  1680 => [
    'CONDITION' => '#^/poselki/kupit-dom/kommunikatsii-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=kommunikaciyami&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1680,
  ],
  1690 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/svet-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=elektrichestvom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1690,
  ],
  1700 => [
    'CONDITION' => '#^/poselki/kupit-dom/svet-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=elektrichestvom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1700,
  ],
  1710 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/gaz-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=gazom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1710,
  ],
  1720 => [
    'CONDITION' => '#^/poselki/kupit-dom/gaz-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=gazom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1720,
  ],
  1730 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/voda-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=vodoprovodom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1730,
  ],
  1740 => [
    'CONDITION' => '#^/poselki/kupit-dom/voda-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=vodoprovodom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1740,
  ],
  1750 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-kommunikatsii/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1750,
  ],
  1760 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-kommunikatsii/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1760,
  ],
  1770 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-kommunikatsii/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1770,
  ],
  1780 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-svet/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1780,
  ],
  1790 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-svet/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1790,
  ],
  1800 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-svet/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1800,
  ],
  1810 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-gaz/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1810,
  ],
  1820 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-gaz/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1820,
  ],
  1830 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-gaz/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1830,
  ],
  1840 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-voda/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1840,
  ],
  1850 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-voda/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1850,
  ],
  1860 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-voda/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1860,
  ],
  1870 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'MKAD_KM=$2&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1870,
  ],
  1880 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'MKAD_KM=$2&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1880,
  ],
  1890 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'SHOSSE_CODE=$1&MKAD_KM=$2',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1890,
  ],
  1900 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-ryadom-s-lesom/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-s-lesom&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1900,
  ],
  1910 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-ryadom-s-lesom/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-s-lesom&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1910,
  ],
  1920 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-ryadom-s-lesom/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-s-lesom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1920,
  ],
  1930 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-u-vody/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-vody&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1930,
  ],
  1940 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-u-vody/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-vody&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1940,
  ],
  1950 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-u-vody/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-vody&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1950,
  ],
  1960 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-snt/(\?(.*))?#',
    'RULE' => 'TYPE_URL=snt&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1960,
  ],
  1970 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-snt/(\?(.*))?#',
    'RULE' => 'TYPE_URL=snt&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1970,
  ],
  1980 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-snt/(\?(.*))?#',
    'RULE' => 'TYPE_URL=snt&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1980,
  ],
  1990 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-shosse-izhs/(\?(.*))?#',
    'RULE' => 'TYPE_URL=izhs&DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 1990,
  ],
  2000 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-shosse-izhs/(\?(.*))?#',
    'RULE' => 'TYPE_URL=izhs&DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2000,
  ],
  2010 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse-izhs/(\?(.*))?#',
    'RULE' => 'TYPE_URL=izhs&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2010,
  ],
  2020 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse/kupit-uchastok/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2020,
  ],
  2030 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse/kupit-dom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2030,
  ],
  2040 => [
    'CONDITION' => '#^/poselki/([^/]+?)-shosse/(\?(.*))?#',
    'RULE' => 'SHOSSE_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2040,
  ],
  2050 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-kommunikatsii/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&DOMA_CODE=noDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2050,
  ],
  2060 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-rayon-kommunikatsii/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&DOMA_CODE=withDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2060,
  ],
  2070 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon-kommunikatsii/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2070,
  ],
  2080 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-svet/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&DOMA_CODE=noDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2080,
  ],
  2090 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-rayon-svet/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&DOMA_CODE=withDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2090,
  ],
  2100 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon-svet/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2100,
  ],
  2110 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-gaz/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&DOMA_CODE=noDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2110,
  ],
  2120 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-rayon-gaz/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&DOMA_CODE=withDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2120,
  ],
  2130 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon-gaz/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2130,
  ],
  2140 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/([^/]+?)-rayon-voda/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&DOMA_CODE=noDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2140,
  ],
  2150 => [
    'CONDITION' => '#^/poselki/kupit-dom/([^/]+?)-rayon-voda/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&DOMA_CODE=withDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2150,
  ],
  2160 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon-voda/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2160,
  ],
  2170 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon/kupit-uchastok/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2170,
  ],
  2180 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon/kupit-dom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2180,
  ],
  2190 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon/(\?(.*))?#',
    'RULE' => 'RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2190,
  ],
  2200 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-s-elektrichestvom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=elektrichestvom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2200,
  ],
  2210 => [
    'CONDITION' => '#^/poselki/kupit-dom-s-elektrichestvom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=elektrichestvom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2210,
  ],
  2220 => [
    'CONDITION' => '#^/poselki/s-elektrichestvom/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2220,
  ],
  2230 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-s-vodoprovodom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=vodoprovodom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2230,
  ],
  2240 => [
    'CONDITION' => '#^/poselki/kupit-dom-s-vodoprovodom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=vodoprovodom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2240,
  ],
  2250 => [
    'CONDITION' => '#^/poselki/s-vodoprovodom/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2250,
  ],
  2260 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-s-gazom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=gazom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2260,
  ],
  2270 => [
    'CONDITION' => '#^/poselki/kupit-dom-s-gazom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=gazom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2270,
  ],
  2280 => [
    'CONDITION' => '#^/poselki/s-gazom/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2280,
  ],
  2290 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-s-kommunikaciyami/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&COMMUN=kommunikaciyami',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2290,
  ],
  2300 => [
    'CONDITION' => '#^/poselki/kupit-dom-s-kommunikaciyami/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&COMMUN=kommunikaciyami',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2300,
  ],
  2310 => [
    'CONDITION' => '#^/poselki/s-kommunikaciyami/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2310,
  ],
  2320 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-snt-([^/]+?)-rayon/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=snt&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2320,
  ],
  2330 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-snt/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=snt',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2330,
  ],
  2340 => [
    'CONDITION' => '#^/poselki/kupit-dom-snt-([^/]+?)-rayon/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=snt&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2340,
  ],
  2350 => [
    'CONDITION' => '#^/poselki/kupit-dom-snt/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=snt',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2350,
  ],
  2360 => [
    'CONDITION' => '#^/poselki/snt/(\?(.*))?#',
    'RULE' => 'TYPE_URL=snt',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2360,
  ],
  2365 => [
    'CONDITION' => '#^/poselki/([^/]+?)-rayon-snt/(\?(.*))?#',
    'RULE' => 'RAYON_CODE=$1&TYPE_URL=snt',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2365,
  ],
  2370 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/do-([0-9]+?)-km-kad-izhs/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=izhs&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2370,
  ],
  2380 => [
    'CONDITION' => '#^/poselki/kupit-dom/do-([0-9]+?)-km-kad-izhs/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=izhs&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2380,
  ],
  2390 => [
    'CONDITION' => '#^/poselki/do-([0-9]+?)-km-kad-izhs/(\?(.*))?#',
    'RULE' => 'TYPE_URL=izhs&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2390,
  ],
  2400 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-izhs-([^/]+?)-rayon/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=izhs&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2400,
  ],
  2410 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-izhs/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=izhs',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2410,
  ],
  2420 => [
    'CONDITION' => '#^/poselki/kupit-dom-izhs-([^/]+?)-rayon/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=izhs&RAYON_CODE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2420,
  ],
  2430 => [
    'CONDITION' => '#^/poselki/kupit-dom-izhs/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=izhs',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2430,
  ],
  2440 => [
    'CONDITION' => '#^/poselki/izhs/(\?(.*))?#',
    'RULE' => 'TYPE_URL=izhs',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2440,
  ],
  2450 => [
    'CONDITION' => '#^/poselki/kupit-uchastok/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2450,
  ],
  2460 => [
    'CONDITION' => '#^/poselki/kupit-dom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2460,
  ],
  2470 => [
    'CONDITION' => '#^/poselki/ryadom-s-lesom/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-s-lesom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2470,
  ],
  2480 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-ryadom-s-lesom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=ryadom-s-lesom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2480,
  ],
  2490 => [
    'CONDITION' => '#^/poselki/kupit-dom-ryadom-s-lesom/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=ryadom-s-lesom',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2490,
  ],
  2500 => [
    'CONDITION' => '#^/poselki/u-vody/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-vody',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2500,
  ],
  2510 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-u-vody/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=u-vody',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2510,
  ],
  2520 => [
    'CONDITION' => '#^/poselki/kupit-dom-u-vody/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=u-vody',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2520,
  ],
  2530 => [
    'CONDITION' => '#^/poselki/u-ozera/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-ozera',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2530,
  ],
  2540 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-u-ozera/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=u-ozera',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2540,
  ],
  2550 => [
    'CONDITION' => '#^/poselki/kupit-dom-u-ozera/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=u-ozera',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2550,
  ],
  2560 => [
    'CONDITION' => '#^/poselki/u-reki/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-reki',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2560,
  ],
  2570 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-u-reki/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=u-reki',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2570,
  ],
  2580 => [
    'CONDITION' => '#^/poselki/kupit-dom-u-reki/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=u-reki',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2580,
  ],
  2590 => [
    'CONDITION' => '#^/poselki/ryadom-zhd-stanciya/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-zhd-stanciya',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2590,
  ],
  2600 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-ryadom-zhd-stanciya/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=ryadom-zhd-stanciya',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2600,
  ],
  2610 => [
    'CONDITION' => '#^/poselki/kupit-dom-ryadom-zhd-stanciya/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=ryadom-zhd-stanciya',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2610,
  ],
  2620 => [
    'CONDITION' => '#^/poselki/ryadom-avtobusnaya-ostanovka/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-avtobusnaya-ostanovka',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2620,
  ],
  2630 => [
    'CONDITION' => '#^/poselki/kupit-uchastok-ryadom-avtobusnaya-ostanovka/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=noDom&TYPE_URL=ryadom-avtobusnaya-ostanovka',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2630,
  ],
  2640 => [
    'CONDITION' => '#^/poselki/kupit-dom-ryadom-avtobusnaya-ostanovka/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&TYPE_URL=ryadom-avtobusnaya-ostanovka',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2640,
  ],
  2645 => [
    'CONDITION' => '#^/poselki/promyshlennye/(\?(.*))?#',
    'RULE' => 'TYPE_URL=promyshlennye',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2645,
  ],
  2650 => [
    'CONDITION' => '#^/poselki/kupit-dom-([0-9]+?)-kv-m/(\?(.*))?#',
    'RULE' => 'DOMA_CODE=withDom&PLOTTAGE=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2650,
  ],
  2660 => [
    'CONDITION' => '#^/poselki/kommunikatsii-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2660,
  ],
  2670 => [
    'CONDITION' => '#^/poselki/svet-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2670,
  ],
  2680 => [
    'CONDITION' => '#^/poselki/gaz-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2680,
  ],
  2690 => [
    'CONDITION' => '#^/poselki/voda-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/poselki/index.php',
    'SORT' => 2690,
  ],
  2700 => [
    'CONDITION' => '#^/poselki/([^/]+?)/reviews/(\?(.*))?#',
    'RULE' => 'ELEMENT_CODE=$1',
    'ID' => 'bitrix:catalog.element',
    'PATH' => '/poselki/reviews.php',
    'SORT' => 2700,
  ],
  2710 => [
    'CONDITION' => '#^/poselki/([^/]+?)/(\?(.*))?#',
    'RULE' => 'ELEMENT_CODE=$1',
    'ID' => 'bitrix:catalog.element',
    'PATH' => '/poselki/detail.php',
    'SORT' => 2710,
  ],
  2720 => [
    'CONDITION' => '#^/doma/v-poselke-([^/]+?)/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=houses&ELEMENT_CODE=$1',
    'ID' => '',
    'PATH' => '/doma/offers-list.php',
    'SORT' => 2720,
  ],
  2730 => [
    'CONDITION' => '#^/doma/([^/]+?)-dom-([0-9]+?)/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=houses&VILLAGE_CODE=$1&ELEMENT_ID=$2',
    'ID' => 'bitrix:catalog.element',
    'PATH' => '/doma/offer-detail.php',
    'SORT' => 2730,
  ],
  2740 => [
    'CONDITION' => '#^/kupit-uchastki/v-poselke-([^/]+?)/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=plots&ELEMENT_CODE=$1',
    'ID' => '',
    'PATH' => '/kupit-uchastki/offers-list.php',
    'SORT' => 2740,
  ],
  2750 => [
    'CONDITION' => '#^/kupit-uchastki/uchastok-([0-9]+?)/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=plots&ELEMENT_ID=$1',
    'ID' => 'bitrix:catalog.element',
    'PATH' => '/kupit-uchastki/offer-detail.php',
    'SORT' => 2750,
  ],
  2760 => [
  	'CONDITION' => '#^/kupit-uchastki/filter/(.+?)/apply/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&SMART_FILTER_PATH=$1&$2',
  	'ID' => 'bitrix:catalog.smart.filter',
  	'PATH' => '/map/index.php',
  	'SORT' => 2760,
  ],
  2770 => [
  	'CONDITION' => '#^/kupit-uchastki/filter/(.+?)/apply/(\?(.*))?#',
  	'RULE' => 'SMART_FILTER_PATH=$1&$2',
  	'ID' => 'bitrix:catalog.smart.filter',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 2770,
  ],
  2780 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2780,
  ],
  2790 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2790,
  ],
  2800 => [
  	'CONDITION' => '#^/kupit-uchastki/do-([0-9]+?)-km-ot-kad/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&MKAD_KM=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2800,
  ],
  2810 => [
  	'CONDITION' => '#^/kupit-uchastki/do-([0-9]+?)-tys-rub/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&PRICE_TYPE=tys&PRICE_URL=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2810,
  ],
  2820 => [
  	'CONDITION' => '#^/kupit-uchastki/do-([0-9,]+?)-mln-rub/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&PRICE_TYPE=mln&PRICE_URL=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2820,
  ],
  2830 => [
  	'CONDITION' => '#^/kupit-uchastki/([0-9]+?)-sotok/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&AREA_TYPE=sotok&AREA_URL=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2830,
  ],
  2840 => [
  	'CONDITION' => '#^/kupit-uchastki/([0-9]+?)-sotki/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&AREA_TYPE=sotki&AREA_URL=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2840,
  ],
  2850 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-class/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&CLASS_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2850,
  ],
  2860 => [
  	'CONDITION' => '#^/kupit-uchastki/s-elektrichestvom/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=elektrichestvom',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2860,
  ],
  2870 => [
  	'CONDITION' => '#^/kupit-uchastki/s-vodoprovodom/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=vodoprovodom',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2870,
  ],
  2880 => [
  	'CONDITION' => '#^/kupit-uchastki/s-gazom/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=gazom',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2880,
  ],
  2890 => [
  	'CONDITION' => '#^/kupit-uchastki/s-kommunikaciyami/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=kommunikaciyami',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2890,
  ],
  2900 => [
  	'CONDITION' => '#^/kupit-uchastki/snt/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=snt',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2900,
  ],
  2910 => [
  	'CONDITION' => '#^/kupit-uchastki/izhs/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=izhs',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2910,
  ],
  2920 => [
  	'CONDITION' => '#^/kupit-uchastki/ryadom-zhd-stanciya/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=ryadom-zhd-stanciya',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2920,
  ],
  2930 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&SHOSSE_CODE=$1&MKAD_KM=$2',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2930,
  ],
  2940 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-do-([0-9]+?)-tys-rub/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&PRICE_TYPE=tys&SHOSSE_CODE=$1&PRICE_URL=$2',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2940,
  ],
  2950 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-do-([0-9,]+?)-mln-rub/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&PRICE_TYPE=mln&SHOSSE_CODE=$1&PRICE_URL=$2',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2950,
  ],
  2960 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-([0-9]+?)-sotok/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&AREA_TYPE=sotok&SHOSSE_CODE=$1&AREA_URL=$2',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2960,
  ],
  2970 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-([0-9]+?)-sotki/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&AREA_TYPE=sotki&SHOSSE_CODE=$1&AREA_URL=$2',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2970,
  ],
  2980 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-kommunikatsii/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=kommunikaciyami&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2980,
  ],
  2990 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-svet/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=elektrichestvom&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 2990,
  ],
  3000 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-gaz/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=gazom&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3000,
  ],
  3010 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-voda/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=vodoprovodom&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3010,
  ],
  3020 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-snt/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=snt&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3020,
  ],
  3030 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-izhs/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=izhs&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3030,
  ],
  3040 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-zhd-stanciya/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=ryadom-zhd-stanciya&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3040,
  ],
  3050 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&RAYON_CODE=$1&MKAD_KM=$2',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3050,
  ],
  3060 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-do-([0-9]+?)-tys-rub/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&PRICE_TYPE=tys&RAYON_CODE=$1&PRICE_URL=$2',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3060,
  ],
  3070 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-do-([0-9,]+?)-mln-rub/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&PRICE_TYPE=mln&RAYON_CODE=$1&PRICE_URL=$2',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3070,
  ],
  3080 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-([0-9]+?)-sotok/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&AREA_TYPE=sotok&RAYON_CODE=$1&AREA_URL=$2',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3080,
  ],
  3090 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-([0-9]+?)-sotki/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&AREA_TYPE=sotki&RAYON_CODE=$1&AREA_URL=$2',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3090,
  ],
  3100 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-kommunikatsii/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=kommunikaciyami&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3100,
  ],
  3110 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-svet/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=elektrichestvom&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3110,
  ],
  3120 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-gaz/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=gazom&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3120,
  ],
  3130 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-voda/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&COMMUN=vodoprovodom&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3130,
  ],
  3140 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-snt/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=snt&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3140,
  ],
  3150 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-izhs/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=izhs&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3150,
  ],
  3160 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-zhd-stanciya/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=ryadom-zhd-stanciya&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3160,
  ],
  3170 => [
  	'CONDITION' => '#^/kupit-uchastki/do-([0-9]+?)-km-kad-izhs/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=izhs&MKAD_KM=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3170,
  ],
  3180 => [
  	'CONDITION' => '#^/kupit-uchastki/ryadom-s-lesom/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=ryadom-s-lesom',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3180,
  ],
  3190 => [
  	'CONDITION' => '#^/kupit-uchastki/u-vody/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=u-vody',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3190,
  ],
  3191 => [
    'CONDITION' => '#^/kupit-uchastki/kommunikatsii-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=plots&COMMUN=kommunikaciyami&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 3191,
  ],
  3192 => [
    'CONDITION' => '#^/kupit-uchastki/gaz-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=plots&COMMUN=gazom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 3192,
  ],
  3193 => [
    'CONDITION' => '#^/kupit-uchastki/svet-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=plots&COMMUN=elektrichestvom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 3193,
  ],
  3194 => [
    'CONDITION' => '#^/kupit-uchastki/voda-do-([0-9]+?)-km-kad/map/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=plots&COMMUN=vodoprovodom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 3194,
  ],
  3195 => [
    'CONDITION' => '#^/kupit-uchastki/u-ozera/map/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=plots&TYPE_URL=u-ozera',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 3195,
  ],
  3196 => [
    'CONDITION' => '#^/kupit-uchastki/u-reki/map/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=plots&TYPE_URL=u-reki',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 3196,
  ],
  3197 => [
    'CONDITION' => '#^/kupit-uchastki/ryadom-avtobusnaya-ostanovka/map/(\?(.*))?#',
    'RULE' => 'OFFER_TYPE=plots&TYPE_URL=ryadom-avtobusnaya-ostanovka',
    'ID' => '',
    'PATH' => '/map/index.php',
    'SORT' => 3197,
  ],
  3200 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-ryadom-s-lesom/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=ryadom-s-lesom&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3200,
  ],
  3210 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-u-vody/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&TYPE_URL=u-vody&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3210,
  ],
  3220 => [
  	'CONDITION' => '#^/kupit-uchastki/map/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots',
  	'ID' => '',
  	'PATH' => '/map/index.php',
  	'SORT' => 3220,
  ],
  3230 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3230,
  ],
  3240 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3240,
  ],
  3250 => [
  	'CONDITION' => '#^/kupit-uchastki/do-([0-9]+?)-km-ot-kad/(\?(.*))?#',
  	'RULE' => 'OFFER_TYPE=plots&MKAD_KM=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3250,
  ],
  3260 => [
  	'CONDITION' => '#^/kupit-uchastki/do-([0-9]+?)-tys-rub/(\?(.*))?#',
  	'RULE' => 'PRICE_TYPE=tys&PRICE_URL=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3260,
  ],
  3270 => [
  	'CONDITION' => '#^/kupit-uchastki/do-([0-9,]+?)-mln-rub/(\?(.*))?#',
  	'RULE' => 'PRICE_TYPE=mln&PRICE_URL=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3270,
  ],
  3280 => [
  	'CONDITION' => '#^/kupit-uchastki/([0-9]+?)-sotok/(\?(.*))?#',
  	'RULE' => 'AREA_TYPE=sotok&AREA_URL=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3280,
  ],
  3290 => [
  	'CONDITION' => '#^/kupit-uchastki/([0-9]+?)-sotki/(\?(.*))?#',
  	'RULE' => 'AREA_TYPE=sotki&AREA_URL=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3290,
  ],
  3300 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-class/(\?(.*))?#',
  	'RULE' => 'CLASS_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3300,
  ],
  3310 => [
  	'CONDITION' => '#^/kupit-uchastki/s-elektrichestvom/(\?(.*))?#',
  	'RULE' => 'COMMUN=elektrichestvom',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3310,
  ],
  3320 => [
  	'CONDITION' => '#^/kupit-uchastki/s-vodoprovodom/(\?(.*))?#',
  	'RULE' => 'COMMUN=vodoprovodom',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3320,
  ],
  3330 => [
  	'CONDITION' => '#^/kupit-uchastki/s-gazom/(\?(.*))?#',
  	'RULE' => 'COMMUN=gazom',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3330,
  ],
  3340 => [
  	'CONDITION' => '#^/kupit-uchastki/s-kommunikaciyami/(\?(.*))?#',
  	'RULE' => 'COMMUN=kommunikaciyami',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3340,
  ],
  3350 => [
  	'CONDITION' => '#^/kupit-uchastki/snt/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=snt',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3350,
  ],
  3360 => [
  	'CONDITION' => '#^/kupit-uchastki/izhs/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=izhs',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3360,
  ],
  3370 => [
  	'CONDITION' => '#^/kupit-uchastki/ryadom-zhd-stanciya/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=ryadom-zhd-stanciya',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3370,
  ],
  3380 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-do-([0-9]+?)-km-kad/(\?(.*))?#',
  	'RULE' => 'SHOSSE_CODE=$1&MKAD_KM=$2',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3380,
  ],
  3390 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-do-([0-9]+?)-tys-rub/(\?(.*))?#',
  	'RULE' => 'PRICE_TYPE=tys&SHOSSE_CODE=$1&PRICE_URL=$2',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3390,
  ],
  3400 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-do-([0-9,]+?)-mln-rub/(\?(.*))?#',
  	'RULE' => 'PRICE_TYPE=mln&SHOSSE_CODE=$1&PRICE_URL=$2',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3400,
  ],
  3410 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-([0-9]+?)-sotok/(\?(.*))?#',
  	'RULE' => 'AREA_TYPE=sotok&SHOSSE_CODE=$1&AREA_URL=$2',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3410,
  ],
  3420 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-([0-9]+?)-sotki/(\?(.*))?#',
  	'RULE' => 'AREA_TYPE=sotki&SHOSSE_CODE=$1&AREA_URL=$2',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3420,
  ],
  3430 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-kommunikatsii/(\?(.*))?#',
  	'RULE' => 'COMMUN=kommunikaciyami&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3430,
  ],
  3440 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-svet/(\?(.*))?#',
  	'RULE' => 'COMMUN=elektrichestvom&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3440,
  ],
  3450 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-gaz/(\?(.*))?#',
  	'RULE' => 'COMMUN=gazom&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3450,
  ],
  3460 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-voda/(\?(.*))?#',
  	'RULE' => 'COMMUN=vodoprovodom&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3460,
  ],
  3470 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-snt/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=snt&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3470,
  ],
  3480 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-izhs/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=izhs&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3480,
  ],
  3490 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-zhd-stanciya/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=ryadom-zhd-stanciya&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3490,
  ],
  3500 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-do-([0-9]+?)-km-kad/(\?(.*))?#',
  	'RULE' => 'RAYON_CODE=$1&MKAD_KM=$2',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3500,
  ],
  3510 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-do-([0-9]+?)-tys-rub/(\?(.*))?#',
  	'RULE' => 'PRICE_TYPE=tys&RAYON_CODE=$1&PRICE_URL=$2',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3510,
  ],
  3520 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-do-([0-9,]+?)-mln-rub/(\?(.*))?#',
  	'RULE' => 'PRICE_TYPE=mln&RAYON_CODE=$1&PRICE_URL=$2',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3520,
  ],
  3530 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-([0-9]+?)-sotok/(\?(.*))?#',
  	'RULE' => 'AREA_TYPE=sotok&RAYON_CODE=$1&AREA_URL=$2',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3530,
  ],
  3540 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-([0-9]+?)-sotki/(\?(.*))?#',
  	'RULE' => 'AREA_TYPE=sotki&RAYON_CODE=$1&AREA_URL=$2',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3540,
  ],
  3550 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-kommunikatsii/(\?(.*))?#',
  	'RULE' => 'COMMUN=kommunikaciyami&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3550,
  ],
  3560 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-svet/(\?(.*))?#',
  	'RULE' => 'COMMUN=elektrichestvom&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3560,
  ],
  3570 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-gaz/(\?(.*))?#',
  	'RULE' => 'COMMUN=gazom&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3570,
  ],
  3580 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-voda/(\?(.*))?#',
  	'RULE' => 'COMMUN=vodoprovodom&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3580,
  ],
  3590 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-snt/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=snt&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3590,
  ],
  3600 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-izhs/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=izhs&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3600,
  ],
  3610 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-zhd-stanciya/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=ryadom-zhd-stanciya&RAYON_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3610,
  ],
  3620 => [
  	'CONDITION' => '#^/kupit-uchastki/do-([0-9]+?)-km-kad-izhs/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=izhs&MKAD_KM=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3620,
  ],
  3630 => [
  	'CONDITION' => '#^/kupit-uchastki/ryadom-s-lesom/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=ryadom-s-lesom',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3630,
  ],
  3640 => [
  	'CONDITION' => '#^/kupit-uchastki/u-vody/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=u-vody',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3640,
  ],
  3650 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-ryadom-s-lesom/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=ryadom-s-lesom&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3650,
  ],
  3660 => [
  	'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-u-vody/(\?(.*))?#',
  	'RULE' => 'TYPE_URL=u-vody&SHOSSE_CODE=$1',
  	'ID' => '',
  	'PATH' => '/kupit-uchastki/index.php',
  	'SORT' => 3660,
  ],
  3670 => [
    'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-do-([0-9]+?)-tysyach/(\?(.*))?#',
    'RULE' => 'PRICE_TYPE=tys&SHOSSE_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3670,
  ],
  3680 => [
    'CONDITION' => '#^/kupit-uchastki/([^/]+?)-shosse-do-([0-9,]+?)-milliona/(\?(.*))?#',
    'RULE' => 'PRICE_TYPE=mln&SHOSSE_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3680,
  ],
  3690 => [
    'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-do-([0-9]+?)-tysyach/(\?(.*))?#',
    'RULE' => 'PRICE_TYPE=tys&RAYON_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3690,
  ],
  3700 => [
    'CONDITION' => '#^/kupit-uchastki/([^/]+?)-rayon-do-([0-9,]+?)-milliona/(\?(.*))?#',
    'RULE' => 'PRICE_TYPE=mln&RAYON_CODE=$1&PRICE_URL=$2',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3700,
  ],
  3710 => [
    'CONDITION' => '#^/kupit-uchastki/kommunikatsii-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'COMMUN=kommunikaciyami&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3710,
  ],
  3720 => [
    'CONDITION' => '#^/kupit-uchastki/gaz-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'COMMUN=gazom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3720,
  ],
  3730 => [
    'CONDITION' => '#^/kupit-uchastki/svet-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'COMMUN=elektrichestvom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3730,
  ],
  3740 => [
    'CONDITION' => '#^/kupit-uchastki/voda-do-([0-9]+?)-km-kad/(\?(.*))?#',
    'RULE' => 'COMMUN=vodoprovodom&MKAD_KM=$1',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3740,
  ],
  3750 => [
    'CONDITION' => '#^/kupit-uchastki/u-ozera/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-ozera',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3750,
  ],
  3760 => [
    'CONDITION' => '#^/kupit-uchastki/u-reki/(\?(.*))?#',
    'RULE' => 'TYPE_URL=u-reki',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3760,
  ],
  3770 => [
    'CONDITION' => '#^/kupit-uchastki/ryadom-avtobusnaya-ostanovka/(\?(.*))?#',
    'RULE' => 'TYPE_URL=ryadom-avtobusnaya-ostanovka',
    'ID' => '',
    'PATH' => '/kupit-uchastki/index.php',
    'SORT' => 3770,
  ],
);
